### ISSUE TITLE
Aliasing @base may not be working correctly

### ISSUE THREAD

**Issue by ethanresnick** [digitalbazaar/jsonld.js#101]
Hi. I'm new to JSON-LD, so please go easy on me :)

I have a document that looks like this:

```
{
  "@context": {
    "id": "@id",
    "type": "@base"
  },
  "id": "4",
  "type": "http://example.com/events/",
  "@type": "http://schema.org/Event",
  //... more data
}
```

My expectation was that, by setting `"type": "@base"` in the context, the `@id` for the object would resolve to `http://example.com/events/4`. Is that indeed what's supposed to happen?

If so, I think there's a bug in the library, as the expanded document that I'm getting instead (from the json-ld playground) is:

```
[
  {
    "@type": [
      "http://schema.org/Event"
    ],
    "@id": "http://json-ld.org/playground/4",
    "@base": [
      "http://example.com/events/"
    ]
  }
]
```

Thanks!

**Comment by dlongley** [comment]
`@base` will only be processed if it appears `@context` of the document, which is why it isn't being used above. So it's not a bug in the library, just a misunderstanding of how `@base` is processed. See: [Base IRI](http://www.w3.org/TR/json-ld/#base-iri). It is a bit odd that `@base` is then treated as a property in the document body, but the API spec doesn't say anything about throwing errors here, rather, it is lenient.

I realize you weren't sure if this was a bug in jsonld.js or not, but, if you do have future questions about JSON-LD syntax, they are better directed here [json-ld.org's github repo](https://github.com/json-ld/json-ld.org). You'll get a much wider audience there; if you ask them here, only the jsonld.js implementers will see them. If it turns out there is a bug in a particular processor you're using, you can always then file an issue on that specific repo and link to the json-ld.org repo issue. :)

**Comment by ethanresnick** [comment]
Thanks @dlongley! I appreciate the clarification and the pointer :)

**Comment by dlongley** [comment]
Sure! :)
