### ISSUE TITLE
Framing with "@embed": "@never" confusing, or bug?

### ISSUE THREAD

**Issue by neothemachine** [digitalbazaar/jsonld.js#117]
The JSON-LD document to frame: https://github.com/ec-melodies/wp02-dcat/blob/master/WP10.jsonld (it's hand-crafted and already has the structure I want, but still, it illustrates the issue).

The frame:
```js
{
  "@context": "https://rawgit.com/ec-melodies/wp02-dcat/master/context.jsonld",
  "@type": "Catalog",
  "datasets": {
    "isPartOf":{ "@embed": "@never"},
    "parts":{ "@embed": "@never"}
  }
}
```

What I expected was that `isPartOf` and `parts` would only contain references, which is actually true, but what additionally happens is that two of three `Dataset` instances are missing! Is this a bug or did I misunderstood what `@embed` does?

**Comment by dlongley** [comment]
@neothemachine,

Those other Datasets aren't missing because of `@embed`, they are missing because you're using duck-typing and they don't match your filter. When framing, you can use either duck-typing or strict typing. To use strict typing, specify an `@type` like so:

http://json-ld.org/playground/#/gist/6e45df1222735707dda1

If you omit an `@type`, then duck-typing will be used. In this case, all of the properties you specify must be present for the data to be appear. Only one of your datasets has both `isPartOf` and `parts`, so the other two are omitted.

Note that in the example I provided above, I also added `@omitDefault: true` to prevent `isPartOf` and `parts` from appearing in the output with a `null` value where those properties aren't present in your datasets. Feel free to mess around with other framing options in the playground to get immediate feedback and a better understanding of what happens.

**Comment by neothemachine** [comment]
Ah ok, that makes sense. Thanks for the example!

**Comment by dlongley** [comment]
Sure!
