### ISSUE TITLE
Authorization with node documentLoader

### ISSUE THREAD

**Issue by agibson-vrnt** [digitalbazaar/jsonld.js#130]
Can't find support anywhere for setting the Authorization header in the node.js documentLoader. Is this supported by the library / are you open to pull requests?

**Comment by dlongley** [comment]
It's not supported but we're open to PRs. One way to do it would be to add a `headers` option here:

https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L1728-L1742

And let people set whatever headers they want -- and then merge in the default `Accept` header on top of any custom headers in the code below.

**Comment by goofballLogic** [comment]
I see suites of tests for the json-ld algorithms, but it's not clear how I add tests for this change which is more to do with the workings of this library than the algorithms. Where do I add the tdd/bdd for this change?

**Comment by dlongley** [comment]
@goofballLogic,

The test suite for jsonld.js needs to be reworked so that it has better support for both spec compliance and local tests. It would be easiest to have two separate test suites (one for each of the aforementioned) because they work quite differently from each other. We just haven't been able to prioritize that work.

So your options are to:

1. Add the non-test parts but leave this issue open indicating we need test(s) for it.
2. Take a stab at setting up a separate `test` dir and mocha framework for running local tests and add your test as the first one.

**Comment by goofballLogic** [comment]
Do you release to npm on a specific cadence? Just wondering when we should expect to get the code in the pull request covering this issue.

**Comment by dlongley** [comment]
@goofballLogic,

Released in 0.4.6: ec73a78d9d51fb032f44cf010a0f0afb5b7c683b

**Comment by goofballLogic** [comment]
awesome.




---- On Wed, 02 Mar 2016 20:33:54 +0000 Dave Longley &lt;notifications@github.com&gt;wrote ---- 




@goofballLogic,

Released in 0.4.6: ec73a78
