### ISSUE TITLE
Using frame to change list of predicates to rdf:List

### ISSUE THREAD

**Issue by amiika** [digitalbazaar/jsonld.js#133]
As you know SPARQL cannot reconstruct lists, but defining "@container":"@list" in JSON-LD response is a nice workaround. I think it would be nice if you could use frame to do this instead of changing the input.

Example of the issue: http://json-ld.org/playground/#/gist/9caa157e76a84b48b8f3

Currently frame changes the "ingredients" id to full uri which is kind of odd.

**Comment by dlongley** [comment]
> Currently frame changes the "ingredients" id to full uri which is kind of odd.

Frame isn't responsible for that change. The main intent of framing is to massage your data into a particular JSON structure for use by an application that has been hard-coded to that structure. This doesn't really have anything to do with converting lists. It's `fromRDF` that can cause a list to be represented via a JSON array and `compact` that can remove the `@list` keyword.

Here, a full URI is used because the term in the new context doesn't match the incoming data. Since the incoming data is not in a list in the data model, it can't use the term, and the property is left as a full URI. The "ingredients" in that example are in a set, not a list. You can force compacted output (regardless of whether you are using framing or not) to use an array by using `"@container": "@set"`. Lists are a different animal because they have a different representation in the data model, whereas sets vs. single items do not; they may only differ in their syntactic representation.

**Comment by amiika** [comment]
Ok, thanks! I was hoping that framing could also be used to change the underlying triples rather than just change the JSON structure. So changing the context in the data is "more right" thing to do if you want to change Set to List.
