### ISSUE TITLE
The following JSON-LD is parsed without an error on the JSON-LD playground

### ISSUE THREAD

**Issue by mitar** [digitalbazaar/jsonld.js#135]
``` json
{
  "@context": {},
  "@id": "id1",
  "@id": "id2",
  "@type": "type1",
  "@type": "type2"
}
```

This JSON-LD violates the [JSON-lD grammar](https://www.w3.org/TR/json-ld/#json-ld-grammar):

> In contrast to JSON, in JSON-LD the keys in objects MUST be unique.

So, the playground should throw an error. Currently it seems that it takes the last value and ignores the rest.

**Comment by dlongley** [comment]
@mitar,

> So, the playground should throw an error. Currently it seems that it takes the last value and ignores the rest.

The playground, like most other JSON-LD implementations, uses the JSON parser that is available on its platform. The behavior you're describing is performed by the parser before the JSON-LD processor ever sees the data. That same behavior is fairly common for JSON parsers across various platforms. A non-native parser would have to be implemented in order to flag this particular error. That wasn't what we were going for in the design, rather, we wanted implementers to be able to use native JSON parsers so we discouraged the use of non-unique keys precisely because they are not accepted by them (and here you see what happens when you try to use them!).

Also, just because the JSON-LD grammar indicates something is forbidden, that doesn't mean that a processor shouldn't try to be more lenient, i.e., following the old maxim "Be conservative in what you send and liberal in what you receive."

**Comment by mitar** [comment]
> Also, just because the JSON-LD grammar indicates something is forbidden, that doesn't mean that a processor shouldn't try to be more lenient, i.e., following the old maxim "Be conservative in what you send and liberal in what you receive."

Sure, but there should be a flag to switch on the more strict behavior. So that I can verify my JSON-LD content for the case when I am a sender. Exactly based on the old maxim: I have to verify that I am conservative in what I send. So, I have to verify that somewhere.

I do agree that the codebase should allow swap the JSON parser used underneath it, for use in other contexts, but the flag for strict behavior above should swap it for a very strict JSON parser.

It is simply useful debugging and learning tool. It is good for one to learn what is the correct syntax and how to use it properly.

I do agree that this should not be the only way, of course. But you do see merit in having a strict version as well, don't you?

**Comment by dlongley** [comment]
@mitar,

> Sure, but there should be a flag to switch on the more strict behavior. So that I can verify my JSON-LD content for the case when I am a sender. Exactly based on the old maxim: I have to verify that I am conservative in what I send. So, I have to verify that somewhere.

This would be useful in a validator, I agree. The playground isn't quite that, however. It's debatable whether it should be -- some people will want to paste technically invalid JSON-LD and see how it gets handled and play with it.

> But you do see merit in having a strict version as well, don't you?

I'm not against someone adding a feature to the playground to turn on strict parsing -- which would require finding a pure JavaScript JSON parser that could be appropriately modified to flag these sorts of errors. I wouldn't want to add all of that code to jsonld.js, however, as it would just be bloat 99.9% of the time.

**Comment by mitar** [comment]
I found this online JSON validator which catches it, but code is not open source, it seems: http://www.freeformatter.com/json-validator.html

**Comment by dlongley** [comment]
Closing as not relevant to this particular repo -- issues related to validation tools/playground/etc. should be filed under json-ld.org.
