### ISSUE TITLE
Compacted result, @vocab and @type

### ISSUE THREAD

**Issue by ariutta** [digitalbazaar/jsonld.js#137]
Is the following the expected behavior? If we compact this input document:

``` jsonld
{
  "@context":
  {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "foaf:homepage": { "@type": "@id" },
    "depiction": { "@id": "foaf:depiction", "@type": "@id" }
  },
  "@id": "http://me.markus-lanthaler.com/",
  "@type": "foaf:Person",
  "foaf:name": "Markus Lanthaler",
  "foaf:homepage": "http://www.markus-lanthaler.com/",
  "depiction": "http://twitter.com/account/profile_image/markuslanthaler"
}
```

We get a compacted document with this `depiction` property:

```
"depiction": "http://twitter.com/account/profile_image/markuslanthaler"
```

[playground](http://tinyurl.com/h2anala)

If we change the property key `depiction` in the input document to `http://xmlns.com/foaf/0.1/depiction`, and compact, we would expect the compacted result to be unchanged, but the compacted `depiction` property is different:

```
"foaf:depiction": "http://twitter.com/account/profile_image/markuslanthaler"
```

[playground](http://tinyurl.com/zxfq8xq)

To get the same compacted result, we need to add this property to the context:

```
"http://xmlns.com/foaf/0.1/depiction": { "@id": "foaf:depiction", "@type": "@id" }
```

[playground](http://tinyurl.com/jfmepka)

It appears that the `@type` specified for `depiction` in the first context does not apply to `http://xmlns.com/foaf/0.1/depiction`, with the result being that [this code](https://github.com/digitalbazaar/jsonld.js/blob/c43f112df04141be81fe468dc582ec90efe8d68f/js/jsonld.js#L5663) is not run to compact `http://xmlns.com/foaf/0.1/depiction` to `depiction`.

[This discussion](https://lists.w3.org/Archives/Public/public-linked-json/2013Mar/0083.html) also seem relevant.

**Comment by dlongley** [comment]
@ariutta,

> If we change the property key depiction in the input document to http://xmlns.com/foaf/0.1/depiction, and compact, we would expect the compacted result to be unchanged, but the compacted depiction property is different...

Your following analysis is correct. You have no term definition that specifies the values for said term should be treated in a special way, i.e., you have no rule that indicates that values of the term `http://xmlns.com/foaf/0.1/depiction` are type-coerced to URLs (there is no `"http://xmlns.com/foaf/0.1/depiction": {"@type": "@id"}` rule).

So, since you've specified the value as a string, it's treated as such, not as a URL. If you don't tell the processor to do something special with a term, it won't do anything special (it has no way to guess what your intent is). Consider the alternate use case -- that there are times that people want to use different terms for different types of values for the same predicate.

**Comment by dlongley** [comment]
Closing as not actionable.
