### ISSUE TITLE
Ship v0.4.12?

### ISSUE THREAD

**Issue by BigBlueHat** [digitalbazaar/jsonld.js#166]
This fix for dealing with HTTPS/Mixed Content stuff is super useful and merged into master:
https://github.com/digitalbazaar/jsonld.js/pull/165

There's also some other small changes that would have benefit to folks depending on jsonld.js.

Could we get v0.4.12 shipped to npm?

Thanks!
🎩

**Comment by BigBlueHat** [comment]
@davidlehn thinking "sticking an `s` in URLs" is about our only option for dealing with the Mixed Content situation...thoughts?

**Comment by davidlehn** [comment]
Changing URLs won't go into jsonld.js itself since there is no way to ensure that is a safe operation.  Applications that use the lib are welcome to do whatever they want in a custom document loader.  For instance, they could rewrite where to fetch a URL based on a whitelist of sites they trust to hold the same content on https as a given http URLs.  Or they could use a proxy if appropriate.  Or just detect the issue and show a warning or error.  In any case, it's not a problem with jsonld.js or one it can directly solve.

**Comment by BigBlueHat** [comment]
@davidlehn yeah...agreed. I'm going to close this as the content and the subject don't really match any longer. Thanks for the assist on the other issue. Cheers!
