### ISSUE TITLE
Test suite is failing due to changes in the json-ld/json-ld.org repo.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/jsonld.js#172]
Tests are failing: https://travis-ci.org/digitalbazaar/jsonld.js/jobs/224895314

Due to: https://github.com/json-ld/json-ld.org/commit/7374dff787690ce6f7781b1079b9023acf550234

**Comment by dlongley** [comment]
We need to do one of two things:

1. Finally completely rework and modernize our ancient test suite.
2. Hack something into the current ancient test suite to skip 1.1 tests.

cc: @davidlehn

**Comment by davidlehn** [comment]
A first pass at skip logic was added a while ago:
https://github.com/digitalbazaar/jsonld.js/commit/41d432e379de9b49da5a516502008d9ac3426734
https://github.com/digitalbazaar/jsonld.js/commit/b79b80c87b1199430fbe0bf6b2d664f9ff68ebd1

It's currently a bad hack that skips all frame tests and url tests that were not passing due to the specs and tests being updated beyond what jsonld.js supports.  In theory all tests that are for 1.1 should be marked as such and the current code will skip them.

**Comment by davidlehn** [comment]
Also see comment: https://github.com/json-ld/json-ld.org/commit/7374dff787690ce6f7781b1079b9023acf550234#commitcomment-21885156

**Comment by dlongley** [comment]
Closing as addressed.
