### ISSUE TITLE
Feature request: add time-slicing code to compact function

### ISSUE THREAD

**Issue by ksuszka** [digitalbazaar/jsonld.js#219]
We have huge json-ld documents (c.a. 1MB) and it seems that compactation can take a few hundreds miliseconds, which blocks node.js thread, which is an issue as we host a web service. It would be nice if long compactations were split into chunks so other requests can be processed on the event loop.

**Comment by davidlehn** [comment]
I'm not sure if anyone has looked into how to do this.  It may be possible but might also just make the code a mess and slower in the general case.  Feel free to explore the idea if you'd like to dig in. 
 Depending on what you're doing, there may be a few things that could help.  If your data is already expanded, the compact call has a skipExpansion flag.  Expansion happens via next tick in 0.4.x and a promise in 0.5.x, so that won't block you but it might be unneeded work.  There's also always regular caching if that's possible.  If those don't help, I'd suggest trying the 'workerpool' module or similar to offload expensive tasks off the main loop.

**Comment by ksuszka** [comment]
Thanks for comment. Unfortunately, we cannot skip expansion as an input form is compacted too, but with a different context. We also considered off-loading this work to a child process (using workerpool, or some other library), but it may not solve the issue completely as passing 1MB of data between processes is expensive too. But we need to do some tests to confirm this.

Just a sidenote:

> Expansion happens via next tick in 0.4.x and a promise in 0.5.x, so that won't block you but it might be unneeded work.

I'm affraid it may be not true. Using promise or process.nextTick in node.js doesn't release event loop by itself. There is a detailed explanation here: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#process-nexttick. If you want to advance the event loop you need to use setImmediate().

**Comment by davidlehn** [comment]
Looks like 0.4.x uses process.nextTick via jsonld.nextTick to do expansion.  I think.  0.5.x uses await on the expand call.  Perhaps you could try manually splitting things up so you at least get a break between expand and compact.  Do the expansion yourself then pass result to compact with skipExpansion set.  That's a minor optimization by might help.

**Comment by dlongley** [comment]
Closing as not actionable/too complex. Running compaction in a web worker/other node.js thread native/user space lib seems to be a way forward.
