### ISSUE TITLE
NPM Install failing to build rdf-canonize@0.2.3

### ISSUE THREAD

**Issue by e-e-e** [digitalbazaar/jsonld.js#232]
I am unable to install jsonld using npm.

This is on a Mac with OSX 10.12.6, node v6.10.3, and npm v3.10.10.

```

> rdf-canonize@0.2.3 install /Users/xxx/node_modules/rdf-canonize
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
../lib/native/IdentifierIssuer.cc:18:13: error: use of undeclared identifier
      'to_string'
  id.append(to_string(counter));
            ^
1 error generated.
make: *** [Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

```

**Comment by e-e-e** [comment]
It compiles and installs ok with node 8. Any thoughts?

**Comment by davidlehn** [comment]
Looks like std::to_string is a C++11 feature.  I'd guess node 6 / npm 3 are using an older compiler or not the right default flags.  Might need to add some macos love in rdf-canonize binding.gyp.  Probably some "condition" clause with "xcode_settings".  Not sure how to make it just for node 6 though.  I'm not sure we have easy access to an environment to test that in.  If anyone can make a patch that handles 6 and 8, that would be great.

**Comment by snegostup** [comment]
Guys check your `GCC` versions. I was also getting errors (though different ones) building `rdf-canonize`, solved by updating `GCC` from `4.8.2` to `4.9.2`

**Comment by inukshuk** [comment]
On a related note `rdf-canonize` requires OpenSSL headers which are included with Node.js, but for example are not included by Electron.js; this is because of potential issues with BoringSSL included in Chromium. It is possible to work around these issues, but requires a great deal of effort if you're trying to ship `rdf-canonize` with an Electron app. Since the dependency seems to cause issues for others as well, I was wondering if turning this into an optional dependency was at all a possibility to make installing easier if you don't need the canonize functionality?

Alternatively, one could could think about making the build easier for Electron.js users; if that's something you'd be interested, I'd be happy to help out and I'd open up a separate issue there if that's OK, just wanted to gauge if that's something you'd be willing to explore.

**Comment by melgish** [comment]
Please Consider:  Ran into this issue trying to run jsonld in the browser.  Would like to see a work-around for browser use that doesn't require every consumer to have node-gyp working in order to install a dependency of a dependency of a dependency that will remain unused.

**Comment by davidlehn** [comment]
This should probably be moved to a rdf-canonize issue, but I'll ask here.  Does anyone know what a fix for this is?  Split the lib?  How would anyone know to install the faster non-js version?  Check if tools are available and skip build if not?  How would that be done?  Maybe node-pre-gyp is useful here?  We don't want to maintain pre built binaries so that sort of thing is a no-go.  Also don't want to ignore build failures if the tools are available since that covers up failures you want to fix.  Suggestions?

**Comment by inukshuk** [comment]
I *think* that what NPM suggests in such a case is, indeed, to split the module and then define an optional dependency on the native module (and appropriate error handling when requiring the module). This way, the installation does not fail if the native module can't be built.

**Comment by melgish** [comment]
Probably an issue for both.  That said, I'm thinking that if rdf-canonize were marked as optional to jsonld, 
 it would still be installed by default, and nobody would break.  People like me using it browser-only could then use 'npm install --no-optional' to work around the failure.  For the other edge case--already using --no-optional but wanting rdf-canonize--it could be marked as a direct dependency by the consumer.

**Comment by Aaron-Sterling** [comment]
@davidlehn You may already know about this, but (to disagree a bit with some others on this thread): the npm documentation about --no-optional does not match up with what really happens. This is a problem that has spanned multiple issues, and multiple versions of both NodeJS and npm. Current behavior appears to be that --no-optional behaves differently in the presence of package-lock.json than it does in the absence of the file, even though that should not matter. So I doubt there's a smooth solution available by making rdf-canonize optional.

**Comment by davidlehn** [comment]
@Aaron-Sterling I haven't really tried the edge cases much.  I was just hoping it would ignore the build failures for the optional native dependency.  Are you saying it won't do that? 
 If anyone wants to test, the code is here: https://github.com/digitalbazaar/rdf-canonize/commits/opt-native

**Comment by Aaron-Sterling** [comment]
@davidlehn I'm not sure. I think it's fair to call the behavior of that option erratic, and a bug that npm has incorrectly claimed was fixed at least twice. So it might be with us for quite a while. Still, for the needs of the average jsonld.js user, maybe everything is fine. One link, for [your reading displeasure](https://github.com/npm/npm/issues/17633).

**Comment by dlongley** [comment]
Closing as we think this is fixed, reopen if not.
