### ISSUE TITLE
Please replace request

### ISSUE THREAD

**Issue by guimard** [digitalbazaar/jsonld.js#420]
Hi,

[request has been deprecated](https://github.com/request/request/issues/3142), could you replace it by another library ?

Cheers,
Xavier

**Comment by aljones15** [comment]
I assigned to me, I will try to replace `request` with [`ky`](https://www.npmjs.com/package/ky) ASAP.

**Comment by dlongley** [comment]
@aljones15, we can use [@digitalbazaar/http-client](https://github.com/digitalbazaar/http-client).

**Comment by aljones15** [comment]
Please note this issue is also related to: https://github.com/digitalbazaar/jsonld.js/issues/200

Which is to replace the documentLoader with a solution that uses the browser's `fetch` api such as axios.
In our case we will be using https://github.com/digitalbazaar/http-client which in turn uses `ky`.

We also need to fix the tests for the documentLoaders:

1. test should rely on an `express` server we start at the beginning of the test suite
2. tests should attempt to resolve contexts/ jsonld documents served as static assets from the express instance.

**Comment by dmitrizagidulin** [comment]
Just to update: This is still on our radar, will get to this as time permits.

**Comment by davidlehn** [comment]
Fixed in 5.0.0.
